// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
	v1 "gfDeomo/api/v1"
)

type IArticle interface {
	List(ctx context.Context, req v1.ContentGetListCommonReq) (v1.ArticleIndexRes, error)
}

var localArticle IArticle

func Article() IArticle {
	if localArticle == nil {
		panic("implement not found for interface IArticle, forgot register?")
	}
	return localArticle
}

func RegisterArticle(i IArticle) {
	localArticle = i
}
