// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gfDeomo/internal/dao/internal"
)

// internalArticleTagsDao is internal type for wrapping internal DAO implements.
type internalArticleTagsDao = *internal.ArticleTagsDao

// articleTagsDao is the data access object for table article_tags.
// You can define custom methods on it to extend its functionality as you wish.
type articleTagsDao struct {
	internalArticleTagsDao
}

var (
	// ArticleTags is globally public accessible object for table article_tags operations.
	ArticleTags = articleTagsDao{
		internal.NewArticleTagsDao(),
	}
)

// Fill with you ideas below.
