// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gfDeomo/internal/dao/internal"
)

// internalCategoriesDao is internal type for wrapping internal DAO implements.
type internalCategoriesDao = *internal.CategoriesDao

// categoriesDao is the data access object for table categories.
// You can define custom methods on it to extend its functionality as you wish.
type categoriesDao struct {
	internalCategoriesDao
}

var (
	// Categories is globally public accessible object for table categories operations.
	Categories = categoriesDao{
		internal.NewCategoriesDao(),
	}
)

// Fill with you ideas below.
