// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gfDeomo/internal/dao/internal"
)

// internalCommentsDao is internal type for wrapping internal DAO implements.
type internalCommentsDao = *internal.CommentsDao

// commentsDao is the data access object for table comments.
// You can define custom methods on it to extend its functionality as you wish.
type commentsDao struct {
	internalCommentsDao
}

var (
	// Comments is globally public accessible object for table comments operations.
	Comments = commentsDao{
		internal.NewCommentsDao(),
	}
)

// Fill with you ideas below.
