// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gfDeomo/internal/dao/internal"
)

// internalLinksDao is internal type for wrapping internal DAO implements.
type internalLinksDao = *internal.LinksDao

// linksDao is the data access object for table links.
// You can define custom methods on it to extend its functionality as you wish.
type linksDao struct {
	internalLinksDao
}

var (
	// Links is globally public accessible object for table links operations.
	Links = linksDao{
		internal.NewLinksDao(),
	}
)

// Fill with you ideas below.
