// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gfDeomo/internal/dao/internal"
)

// internalNavigationsDao is internal type for wrapping internal DAO implements.
type internalNavigationsDao = *internal.NavigationsDao

// navigationsDao is the data access object for table navigations.
// You can define custom methods on it to extend its functionality as you wish.
type navigationsDao struct {
	internalNavigationsDao
}

var (
	// Navigations is globally public accessible object for table navigations operations.
	Navigations = navigationsDao{
		internal.NewNavigationsDao(),
	}
)

// Fill with you ideas below.
