// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gfDeomo/internal/dao/internal"
)

// internalPagesDao is internal type for wrapping internal DAO implements.
type internalPagesDao = *internal.PagesDao

// pagesDao is the data access object for table pages.
// You can define custom methods on it to extend its functionality as you wish.
type pagesDao struct {
	internalPagesDao
}

var (
	// Pages is globally public accessible object for table pages operations.
	Pages = pagesDao{
		internal.NewPagesDao(),
	}
)

// Fill with you ideas below.
