// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gfDeomo/internal/dao/internal"
)

// internalPasswordResetsDao is internal type for wrapping internal DAO implements.
type internalPasswordResetsDao = *internal.PasswordResetsDao

// passwordResetsDao is the data access object for table password_resets.
// You can define custom methods on it to extend its functionality as you wish.
type passwordResetsDao struct {
	internalPasswordResetsDao
}

var (
	// PasswordResets is globally public accessible object for table password_resets operations.
	PasswordResets = passwordResetsDao{
		internal.NewPasswordResetsDao(),
	}
)

// Fill with you ideas below.
