// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gfDeomo/internal/dao/internal"
)

// internalSystemsDao is internal type for wrapping internal DAO implements.
type internalSystemsDao = *internal.SystemsDao

// systemsDao is the data access object for table systems.
// You can define custom methods on it to extend its functionality as you wish.
type systemsDao struct {
	internalSystemsDao
}

var (
	// Systems is globally public accessible object for table systems operations.
	Systems = systemsDao{
		internal.NewSystemsDao(),
	}
)

// Fill with you ideas below.
