// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// ArticleTags is the golang structure for table article_tags.
type ArticleTags struct {
	ArticleId uint `json:"articleId" description:""` //
	TagId     uint `json:"tagId"     description:""` //
}
