// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Articles is the golang structure for table articles.
type Articles struct {
	Id           uint        `json:"id"           description:""`                //
	Title        string      `json:"title"        description:"文章标题"`            // 文章标题
	Keyword      string      `json:"keyword"      description:"keywords"`        // keywords
	Desc         string      `json:"desc"         description:"描述"`              // 描述
	Content      string      `json:"content"      description:"文章内容,markdown格式"` // 文章内容,markdown格式
	UserId       int         `json:"userId"       description:"文章编写人,对应users表"`  // 文章编写人,对应users表
	CateId       int         `json:"cateId"       description:"文章分类"`            // 文章分类
	CommentCount int         `json:"commentCount" description:"评论数量"`            // 评论数量
	ReadCount    int         `json:"readCount"    description:"阅读数量"`            // 阅读数量
	Status       int         `json:"status"       description:"文章状态:0-公开;1-私密"`  // 文章状态:0-公开;1-私密
	Sort         int         `json:"sort"         description:"排序"`              // 排序
	CreatedAt    *gtime.Time `json:"createdAt"    description:""`                //
	UpdatedAt    *gtime.Time `json:"updatedAt"    description:""`                //
	HtmlContent  string      `json:"htmlContent"  description:"文章内容,html格式"`     // 文章内容,html格式
	ListPic      string      `json:"listPic"      description:"文章列表图"`           // 文章列表图
}
