// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Categories is the golang structure for table categories.
type Categories struct {
	Id        uint        `json:"id"        description:""` //
	ParentId  int         `json:"parentId"  description:""` //
	Lft       int         `json:"lft"       description:""` //
	Rgt       int         `json:"rgt"       description:""` //
	Depth     int         `json:"depth"     description:""` //
	Name      string      `json:"name"      description:""` //
	CreatedAt *gtime.Time `json:"createdAt" description:""` //
	UpdatedAt *gtime.Time `json:"updatedAt" description:""` //
}
