// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Comments is the golang structure for table comments.
type Comments struct {
	Id         uint        `json:"id"         description:""` //
	ArticleId  int         `json:"articleId"  description:""` //
	ParentId   int         `json:"parentId"   description:""` //
	Content    string      `json:"content"    description:""` //
	Name       string      `json:"name"       description:""` //
	Email      string      `json:"email"      description:""` //
	Website    string      `json:"website"    description:""` //
	Avatar     string      `json:"avatar"     description:""` //
	Ip         string      `json:"ip"         description:""` //
	City       string      `json:"city"       description:""` //
	UserId     int         `json:"userId"     description:""` //
	TargetName string      `json:"targetName" description:""` //
	CreatedAt  *gtime.Time `json:"createdAt"  description:""` //
	UpdatedAt  *gtime.Time `json:"updatedAt"  description:""` //
}
