// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Links is the golang structure for table links.
type Links struct {
	Id        uint        `json:"id"        description:""` //
	Name      string      `json:"name"      description:""` //
	Url       string      `json:"url"       description:""` //
	Sequence  int         `json:"sequence"  description:""` //
	CreatedAt *gtime.Time `json:"createdAt" description:""` //
	UpdatedAt *gtime.Time `json:"updatedAt" description:""` //
}
