// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Migrations is the golang structure for table migrations.
type Migrations struct {
	Migration string `json:"migration" description:""` //
	Batch     int    `json:"batch"     description:""` //
}
