// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Navigations is the golang structure for table navigations.
type Navigations struct {
	Id            uint        `json:"id"            description:""`                  //
	Name          string      `json:"name"          description:""`                  //
	Url           string      `json:"url"           description:""`                  //
	State         int         `json:"state"         description:"0-正常显示;1-隐藏"`       // 0-正常显示;1-隐藏
	Sequence      int         `json:"sequence"      description:"排序"`                // 排序
	NavType       int         `json:"navType"       description:"导航类型:0-自定义;1-分类导航"` // 导航类型:0-自定义;1-分类导航
	ArticleCateId int         `json:"articleCateId" description:"文章分类id"`            // 文章分类id
	CreatedAt     *gtime.Time `json:"createdAt"     description:""`                  //
	UpdatedAt     *gtime.Time `json:"updatedAt"     description:""`                  //
}
