// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Pages is the golang structure for table pages.
type Pages struct {
	Id          uint        `json:"id"          description:""`             //
	Title       string      `json:"title"       description:"页面标题"`         // 页面标题
	LinkAlias   string      `json:"linkAlias"   description:"链接别名"`         // 链接别名
	Keyword     string      `json:"keyword"     description:"关键词"`          // 关键词
	Desc        string      `json:"desc"        description:"描述"`           // 描述
	Content     string      `json:"content"     description:"页面markdown格式"` // 页面markdown格式
	HtmlContent string      `json:"htmlContent" description:"页面html"`       // 页面html
	CreatedAt   *gtime.Time `json:"createdAt"   description:""`             //
	UpdatedAt   *gtime.Time `json:"updatedAt"   description:""`             //
}
