// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Systems is the golang structure for table systems.
type Systems struct {
	Id    uint   `json:"id"    description:""` //
	Key   string `json:"key"   description:""` //
	Value string `json:"value" description:""` //
}
