// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Users is the golang structure for table users.
type Users struct {
	Id            uint        `json:"id"            description:""`       //
	Name          string      `json:"name"          description:""`       //
	Email         string      `json:"email"         description:""`       //
	Password      string      `json:"password"      description:""`       //
	RememberToken string      `json:"rememberToken" description:""`       //
	CreatedAt     *gtime.Time `json:"createdAt"     description:""`       //
	UpdatedAt     *gtime.Time `json:"updatedAt"     description:""`       //
	UserPic       string      `json:"userPic"       description:"博客用户头像"` // 博客用户头像
}
