// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// NavigationsDao is the data access object for table navigations.
type NavigationsDao struct {
	table   string             // table is the underlying table name of the DAO.
	group   string             // group is the database configuration group name of current DAO.
	columns NavigationsColumns // columns contains all the column names of Table for convenient usage.
}

// NavigationsColumns defines and stores column names for table navigations.
type NavigationsColumns struct {
	Id            string //
	Name          string //
	Url           string //
	State         string // 0-正常显示;1-隐藏
	Sequence      string // 排序
	NavType       string // 导航类型:0-自定义;1-分类导航
	ArticleCateId string // 文章分类id
	CreatedAt     string //
	UpdatedAt     string //
}

//  navigationsColumns holds the columns for table navigations.
var navigationsColumns = NavigationsColumns{
	Id:            "id",
	Name:          "name",
	Url:           "url",
	State:         "state",
	Sequence:      "sequence",
	NavType:       "nav_type",
	ArticleCateId: "article_cate_id",
	CreatedAt:     "created_at",
	UpdatedAt:     "updated_at",
}

// NewNavigationsDao creates and returns a new DAO object for table data access.
func NewNavigationsDao() *NavigationsDao {
	return &NavigationsDao{
		group:   "default",
		table:   "navigations",
		columns: navigationsColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *NavigationsDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *NavigationsDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *NavigationsDao) Columns() NavigationsColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *NavigationsDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *NavigationsDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *NavigationsDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
