// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// ArticleTags is the golang structure of table article_tags for DAO operations like Where/Data.
type ArticleTags struct {
	g.Meta    `orm:"table:article_tags, do:true"`
	ArticleId interface{} //
	TagId     interface{} //
}
