// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Articles is the golang structure of table articles for DAO operations like Where/Data.
type Articles struct {
	g.Meta       `orm:"table:articles, do:true"`
	Id           interface{} //
	Title        interface{} // 文章标题
	Keyword      interface{} // keywords
	Desc         interface{} // 描述
	Content      interface{} // 文章内容,markdown格式
	UserId       interface{} // 文章编写人,对应users表
	CateId       interface{} // 文章分类
	CommentCount interface{} // 评论数量
	ReadCount    interface{} // 阅读数量
	Status       interface{} // 文章状态:0-公开;1-私密
	Sort         interface{} // 排序
	CreatedAt    *gtime.Time //
	UpdatedAt    *gtime.Time //
	HtmlContent  interface{} // 文章内容,html格式
	ListPic      interface{} // 文章列表图
}
