// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Comments is the golang structure of table comments for DAO operations like Where/Data.
type Comments struct {
	g.Meta     `orm:"table:comments, do:true"`
	Id         interface{} //
	ArticleId  interface{} //
	ParentId   interface{} //
	Content    interface{} //
	Name       interface{} //
	Email      interface{} //
	Website    interface{} //
	Avatar     interface{} //
	Ip         interface{} //
	City       interface{} //
	UserId     interface{} //
	TargetName interface{} //
	CreatedAt  *gtime.Time //
	UpdatedAt  *gtime.Time //
}
