// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Navigations is the golang structure of table navigations for DAO operations like Where/Data.
type Navigations struct {
	g.Meta        `orm:"table:navigations, do:true"`
	Id            interface{} //
	Name          interface{} //
	Url           interface{} //
	State         interface{} // 0-正常显示;1-隐藏
	Sequence      interface{} // 排序
	NavType       interface{} // 导航类型:0-自定义;1-分类导航
	ArticleCateId interface{} // 文章分类id
	CreatedAt     *gtime.Time //
	UpdatedAt     *gtime.Time //
}
