// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Pages is the golang structure of table pages for DAO operations like Where/Data.
type Pages struct {
	g.Meta      `orm:"table:pages, do:true"`
	Id          interface{} //
	Title       interface{} // 页面标题
	LinkAlias   interface{} // 链接别名
	Keyword     interface{} // 关键词
	Desc        interface{} // 描述
	Content     interface{} // 页面markdown格式
	HtmlContent interface{} // 页面html
	CreatedAt   *gtime.Time //
	UpdatedAt   *gtime.Time //
}
