// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// PasswordResets is the golang structure of table password_resets for DAO operations like Where/Data.
type PasswordResets struct {
	g.Meta    `orm:"table:password_resets, do:true"`
	Email     interface{} //
	Token     interface{} //
	CreatedAt *gtime.Time //
}
