// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Systems is the golang structure of table systems for DAO operations like Where/Data.
type Systems struct {
	g.Meta `orm:"table:systems, do:true"`
	Id     interface{} //
	Key    interface{} //
	Value  interface{} //
}
